"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { TrendingUp, Phone, Calendar, Clock, DollarSign, Users, Activity, ArrowUpRight, ArrowDownRight } from "lucide-react";

interface Appointment {
  id: string;
  time: string;
  patient: string;
  service: string;
  price: number;
  status: "confirmed" | "completed" | "no_show";
  doctor: string;
}

// Simulated live data
const MOCK_APPOINTMENTS: Appointment[] = [
  { id: "1", time: "09:00", patient: "Fatima Z.", service: "Consultation", price: 3000, status: "completed", doctor: "Dr. Mansouri" },
  { id: "2", time: "09:30", patient: "Karim B.", service: "Teeth Cleaning", price: 5000, status: "completed", doctor: "Dr. Belkacem" },
  { id: "3", time: "10:00", patient: "Amira H.", service: "Root Canal", price: 25000, status: "completed", doctor: "Dr. Mansouri" },
  { id: "4", time: "10:45", patient: "Youcef D.", service: "Orthodontic Consult", price: 4000, status: "confirmed", doctor: "Dr. Mansouri" },
  { id: "5", time: "11:30", patient: "Nadia M.", service: "Teeth Whitening", price: 15000, status: "confirmed", doctor: "Dr. Belkacem" },
  { id: "6", time: "14:00", patient: "Omar S.", service: "Consultation", price: 3000, status: "confirmed", doctor: "Dr. Mansouri" },
  { id: "7", time: "14:30", patient: "Lina K.", service: "X-Ray", price: 4000, status: "confirmed", doctor: "Dr. Belkacem" },
  { id: "8", time: "15:00", patient: "Mehdi R.", service: "Root Canal", price: 25000, status: "confirmed", doctor: "Dr. Mansouri" },
  { id: "9", time: "16:00", patient: "Sami Y.", service: "Consultation", price: 3000, status: "confirmed", doctor: "Dr. Belkacem" },
  { id: "10", time: "16:30", patient: "Houda L.", service: "Teeth Cleaning", price: 5000, status: "confirmed", doctor: "Dr. Mansouri" },
];

const FEED = [
  { time: "08:47", text: "AI booked Fatima Z. for Dr. Mansouri (Consultation)", type: "booking" },
  { time: "08:52", text: "AI quoted 5,000 DA for teeth cleaning to caller +213661XX", type: "quote" },
  { time: "09:01", text: "SMS confirmation sent to Karim B.", type: "sms" },
  { time: "09:15", text: "AI detected triage keyword 'bleeding' - escalated to emergency line", type: "alert" },
  { time: "09:22", text: "AI booked Amira H. for root canal (Dr. Mansouri)", type: "booking" },
  { time: "09:45", text: "24h reminder SMS sent to 4 patients for tomorrow", type: "sms" },
  { time: "10:05", text: "AI handled patient inquiry about parking - resolved without human.", type: "quote" },
];

export default function ClinicDashboard({ params }: { params: Promise<{ clinicId: string }> }) {
  const [now, setNow] = useState("");
  const [selectedDoctor, setSelectedDoctor] = useState("all");
  const [clinicData, setClinicData] = useState<any>(null);

  useEffect(() => {
    // Simulate fetching the configuration generated by the Architect
    const fetchConfig = async () => {
      try {
        const res = await fetch(`http://localhost:8000/v1/analytics/clinic-config?id=${(await params).clinicId}`);
        const data = await res.json();
        setClinicData(data);
      } catch (e) {
        console.log("Using mock data as fallback");
      }
    };
    fetchConfig();

    setNow(new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" }));

    const t = setInterval(() => setNow(new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })), 60000);
    return () => clearInterval(t);
  }, []);

  const filtered = selectedDoctor === "all" ? MOCK_APPOINTMENTS : MOCK_APPOINTMENTS.filter(a => a.doctor === selectedDoctor);
  const totalRevenue = filtered.reduce((s, a) => s + a.price, 0);
  const completedCount = filtered.filter(a => a.status === "completed").length;

  const stats = [
    { label: "Revenue Today", value: `${totalRevenue.toLocaleString("en-US")} DA`, icon: DollarSign, change: "+23%", up: true },
    { label: "Appointments", value: filtered.length.toString(), icon: Calendar, change: "+5", up: true },
    { label: "Calls Handled by AI", value: "14", icon: Phone, change: "100%", up: true },
    { label: "Avg. Speed to Book", value: "38s", icon: Clock, change: "-12s", up: true },
  ];

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      {/* TOP BAR */}
      <div className="border-b border-white/5 bg-[#0a0a0a]/90 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-8 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
            <h1 className="text-sm font-bold tracking-widest uppercase text-[#D4AF37]">Clinic OS</h1>
            <span className="text-[10px] text-white/20 border-l border-white/10 pl-4">Cabinet Dentaire</span>
          </div>
          <div className="flex items-center gap-6">
            <div className="flex gap-2">
              {["all", "Dr. Mansouri", "Dr. Belkacem"].map(d => (
                <button key={d} onClick={() => setSelectedDoctor(d)} className={`px-3 py-1.5 rounded text-[10px] uppercase tracking-widest font-semibold border transition-all ${selectedDoctor === d ? "bg-[#D4AF37]/20 border-[#D4AF37]/50 text-[#D4AF37]" : "border-white/10 text-white/40 hover:border-white/20"}`}>
                  {d === "all" ? "All Doctors" : d}
                </button>
              ))}
            </div>
            <span className="text-xs text-white/30">{now}</span>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-8 py-8">
        {/* STATS GRID */}
        <div className="grid grid-cols-4 gap-4 mb-8">
          {stats.map((stat, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }} className="p-5 rounded-xl border border-white/5 bg-white/[0.02] hover:border-white/10 transition-all">
              <div className="flex items-center justify-between mb-3">
                <stat.icon size={16} className="text-[#D4AF37]" />
                <span className={`text-[10px] font-bold flex items-center gap-0.5 ${stat.up ? "text-green-400" : "text-red-400"}`}>
                  {stat.up ? <ArrowUpRight size={10} /> : <ArrowDownRight size={10} />} {stat.change}
                </span>
              </div>
              <p className="text-2xl font-bold tracking-tight">{stat.value}</p>
              <p className="text-[10px] text-white/30 uppercase tracking-widest mt-1">{stat.label}</p>
            </motion.div>
          ))}
        </div>

        <div className="grid grid-cols-3 gap-6">
          {/* APPOINTMENTS TABLE */}
          <div className="col-span-2 rounded-xl border border-white/5 bg-white/[0.02] overflow-hidden">
            <div className="px-6 py-4 border-b border-white/5 flex items-center justify-between">
              <h2 className="text-sm font-bold uppercase tracking-widest flex items-center gap-2"><Calendar size={14} className="text-[#D4AF37]" /> Today&apos;s Schedule</h2>
              <span className="text-[10px] text-white/30">{filtered.length} appointments</span>
            </div>
            <div className="divide-y divide-white/5">
              {filtered.map((apt, i) => (
                <motion.div key={apt.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: i * 0.05 }} className="px-6 py-3.5 flex items-center justify-between hover:bg-white/[0.02] transition-colors">
                  <div className="flex items-center gap-4">
                    <span className="text-xs font-mono text-white/30 w-12">{apt.time}</span>
                    <div>
                      <p className="text-sm font-semibold">{apt.patient}</p>
                      <p className="text-[10px] text-white/40">{apt.service} &middot; {apt.doctor}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-4">
                    <span className="text-sm font-bold text-[#D4AF37]">{apt.price.toLocaleString("en-US")} DA</span>
                    <span className={`text-[9px] px-2 py-0.5 rounded uppercase font-bold ${
                      apt.status === "completed" ? "bg-green-500/20 text-green-400" :
                      apt.status === "no_show" ? "bg-red-500/20 text-red-400" :
                      "bg-blue-500/20 text-blue-400"
                    }`}>{apt.status}</span>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>

          {/* AI LIVE FEED */}
          <div className="rounded-xl border border-white/5 bg-white/[0.02] overflow-hidden">
            <div className="px-6 py-4 border-b border-white/5">
              <h2 className="text-sm font-bold uppercase tracking-widest flex items-center gap-2"><Activity size={14} className="text-[#D4AF37]" /> AI Live Feed</h2>
            </div>
            <div className="divide-y divide-white/5 max-h-[400px] overflow-y-auto">
              {FEED.map((item, i) => (
                <motion.div key={i} initial={{ opacity: 0, x: 10 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: i * 0.1 }} className="px-5 py-3.5">
                  <div className="flex items-start gap-3">
                    <div className={`w-1.5 h-1.5 rounded-full mt-1.5 shrink-0 ${
                      item.type === "alert" ? "bg-red-400" :
                      item.type === "booking" ? "bg-green-400" :
                      item.type === "sms" ? "bg-blue-400" : "bg-[#D4AF37]"
                    }`} />
                    <div>
                      <p className="text-xs text-white/70 leading-relaxed">{item.text}</p>
                      <p className="text-[9px] text-white/20 mt-1">{item.time}</p>
                    </div>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
